### PR TITLE
Delete branch after merge

### LINKED ISSUE #11: Remove branch after merging PR
We should at least provide an option to delete the PR branch. Maybe it could be enabled by default.

### PR DESCRIPTION
**Pull request by christiansiegel**
Fixes #11

### CODE REVIEW

**Comment by niiku** [comment]
Looks good to me. But isn‘t there an option on the merge pr api, which deletes the branch afterwards?

**Comment by christiansiegel** [comment]
I can't find any..

**Comment by joachimprinzbach** [comment]
@christiansiegel  Delete this branch pls :-D

**Comment by joachimprinzbach** [comment]
@niiku according to the docs, this option does not exist in the rest api for merging the PR: https://docs.atlassian.com/DAC/rest/stash/3.0.1/stash-rest.html#idp999792

**Comment by niiku** [comment]
Yeah, I saw that too - Just thought the checkbox in the UI corresponds to the same request as the merge itself.

**Pull request merged**
