### PR TITLE
add simple travis config

### LINKED ISSUE #12: Create travis / circleci build
If we want to have the utility open source, we should use open source CI tools to build and publish to dockerhub

### PR DESCRIPTION
**Pull request by joachimprinzbach**
Add Travis build

closes #12

### CODE REVIEW

**Comment by christiansiegel** [comment]
Well, it seems I don't have the permissions to add a Travis pipeline to the repo...
Plus, it would be nice to have it push the image to dockerhub.

**Comment by joachimprinzbach** [comment]
I added both of it ;-) sorry, forgot to write that its WIP. Should be done now ;-) 
https://hub.docker.com/repository/docker/baloiseincubator/gitopscli

**Comment by joachimprinzbach** [comment]
Just tags latest on every branch, can be extended later on if we need proper versioning

**Comment by joachimprinzbach** [comment]
@niiku I think we can delete the "baloise-ci" branch now, we can just use a baseimage based on the one from dockerhub.

**Pull request merged**
