### PR TITLE
deploy: print error message if values file not found

### PR DESCRIPTION
**Pull request by christiansiegel**

### CODE REVIEW

**Comment by christiansiegel** [comment]
Raising an exception is a bit ugly, don't you think?

**Comment by joachimprinzbach** [comment]
imo sys.exit is ugly - but i wrote my first line of pythin on wednesday, so up to you to choose the better solution. As long as the caller gets an appropriate message and exit code im fine with either solution

**Comment by joachimprinzbach** [comment]
Just for consistency: https://github.com/baloise-incubator/gitopscli/blob/master/gitopscli/commands/sync_apps.py#L137
Then this should be changes as well

**Comment by joachimprinzbach** [comment]
One option: throw exceptions with messages and catch them globally. Handle them there, log the message and exit

**Comment by christiansiegel** [comment]
`sys.exit` is not the worst, e.g. try-finally still works. But handling the exceptions globally is even better, true.

**Pull request merged**
